"use client";
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'app.name': '正道驿站',
    'app.subtitle': '正心正念，互相成就',
    'app.slogan': '信任不是评价出来的，而是在真实交往中被记录、被验证、被长期沉淀出来的',
    'nav.home': '首页',
    'nav.community': '本站导航',
    'nav.dashboard': '控制台',
    'nav.profile.mindset': '心性档案',
    'nav.profile.trust': '可信展示',
    'nav.projects': '项目中心',
    'nav.activities': '活动中心',
    'nav.people': '发现广场',
    'nav.ai': 'AI工具',
    'nav.templates': '对外展示',
    'nav.relationships': '合作关系',
    'nav.records': '认知留痕',
    'nav.cooperation': '合作中心',
    'nav.archives': '记录中心',
    'nav.access': '授权查询',
    'nav.mediation': '协调中心',
    'nav.salons': '正念沙龙',
    'nav.communities': '成长共同体',
    'nav.mindset': '心性档案',
    'nav.profile': '用户资料',
    'nav.search': '查询关系',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.logout': '退出',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.loading': '加载中...',
    'common.empty': '暂无数据',
    'common.more': '查看更多',
    'common.back': '返回',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.all': '全部',
    'common.view': '查看',
    'auth.login.title': '登录',
    'auth.login.email': '邮箱',
    'auth.login.password': '密码',
    'auth.login.remember': '记住我',
    'auth.login.forgot': '忘记密码？',
    'auth.login.button': '登录',
    'auth.login.noAccount': '还没有账号？',
    'auth.register.title': '注册',
    'auth.register.name': '真实姓名',
    'auth.register.email': '邮箱',
    'auth.register.password': '密码',
    'auth.register.confirmPassword': '确认密码',
    'auth.register.agreement': '我已阅读并同意《正心承诺与认知留痕规则》',
    'auth.register.button': '完成注册',
    'auth.register.hasAccount': '已有账号？',
    'home.hero.title': '正道驿站',
    'home.hero.subtitle': '让正心伙伴凝成一股产业力量！',
    'home.hero.description': '信任不是评价出来的，而是在真实交往中被记录、被验证、被长期沉淀出来的',
    'home.hero.start': '开始使用',
    'home.feature.consensus': '根本共识',
    'home.feature.consensus.desc': '正心正念，互相成就',
    'home.feature.communication': '沟通共识',
    'home.feature.communication.desc': '正向思考，建设性沟通，改过责善',
    'home.feature.trace': '沟通共识',
    'home.feature.trace.desc': '正向思考，建设性沟通，改过责善',
    'home.feature.auth': '多方授权',
    'home.feature.auth.desc': '敏感信息需授权访问，保护各方隐私',
    'home.feature.mindset': '心性成长',
    'home.feature.mindset.desc': '正念训练，安住当下',
    'home.highlight.privacy': '伙伴优选',
    'home.highlight.privacy.desc': '交往沉淀，成就优质伙伴',
    'home.highlight.neutral': '平台存档',
    'home.highlight.neutral.desc': '自主记录，授权查询，恶行入档',
    'home.highlight.blockchain': '行为留痕',
    'home.highlight.blockchain.desc': '敢于留痕，可靠看得见',
    'home.cta.title': '构建一个互信的圈子',
    'home.cta.description': '让合作有迹可循，让成长在真实交往中发生',
    'home.cta.button': '立即注册',
    'home.disclaimer': '本平台不对任何争议作价值判断，仅记录多方陈述与过程事实',
    'dashboard.welcome': '欢迎回来',
    'dashboard.description': '管理您的信任关系与留痕记录',
    'dashboard.stats.relationships': '合作关系',
    'dashboard.stats.records': '留痕记录',
    'dashboard.stats.requests': '待处理请求',
    'dashboard.activity.title': '最近活动',
    'dashboard.activity.newRelationship': '创建了新的合作关系',
    'dashboard.activity.newRecord': '添加了新的认知留痕',
    'dashboard.activity.newRequest': '收到了新的授权请求',
    'dashboard.quick.title': '快捷操作',
    'dashboard.quick.newRelationship': '新建关系',
    'dashboard.quick.newRecord': '添加记录',
    'dashboard.quick.search': '查询授权',
    'dashboard.quick.mediation': '协调中心',
    'relationship.title': '合作关系管理',
    'relationship.description': '管理您的商业合作、投资、雇佣等关系',
    'relationship.create': '创建关系',
    'relationship.search': '搜索合作关系...',
    'relationship.type.all': '所有类型',
    'relationship.type.business': '商业交易',
    'relationship.type.investment': '投资',
    'relationship.type.partnership': '合伙',
    'relationship.type.employment': '雇佣',
    'relationship.status.all': '所有状态',
    'relationship.status.active': '进行中',
    'relationship.status.ended': '已结束',
    'relationship.status.disputed': '存在分歧',
    'relationship.table.title': '关系标题',
    'relationship.table.type': '类型',
    'relationship.table.status': '状态',
    'relationship.table.participants': '参与方',
    'relationship.table.date': '开始日期',
    'mediation.title': '协调中心',
    'mediation.description': '引入第三方协调人，公正处理合作分歧',
    'mediation.apply': '申请协调',
    'mediation.status.pending': '进行中',
    'mediation.status.resolved': '已解决',
    'mediation.status.failed': '协调失败',
    'mediation.mediator': '协调员',
    'mediation.parties': '当事方',
    'mediation.description.label': '问题描述',
    'profile.title': '个人中心',
    'profile.overview': '概览',
    'profile.stats': '数据统计',
    'profile.trustScore': '信任指数',
    'profile.relationships': '合作关系',
    'profile.records': '留痕记录',
    'profile.edit': '编辑资料',
    'mindset.title': '心性档案',
    'mindset.description': '记录您的正念修习与心性成长历程',
    'mindset.level': '心性层级',
    'mindset.practice': '修习记录',
    'mindset.reflection': '反思日志',
    'activities.title': '活动中心',
    'activities.description': '发现并参与各类线上线下活动',
    'activities.upcoming': '即将开始',
    'activities.ongoing': '正在进行',
    'activities.ended': '已结束',
    'projects.title': '项目中心',
    'projects.description': '让更多的伙伴了解您的项目',
    'salons.title': '正念沙龙',
    'salons.subtitle': '探索内心，建立深度连接',
    'communities.title': '成长共同体',
    'communities.subtitle': '与正心伙伴一起成长，共同成就',
    'people.title': '发现伙伴',
    'people.description': '找到志同道合的合作伙伴',
    'people.searchPlaceholder': '用邮箱搜索...',
    'people.search': '搜索伙伴',
    'people.following': '关注清单',
    'common.participants': '人参与',
    'activity.create': '发起活动',
    'activity.online': '线上',
    'activity.offline': '线下',
    'communities.create': '创建共同体',
    'communities.join': '加入',
    'communities.members': '位成员',
    'communities.searchPlaceholder': '搜索共同体...',
    'records.title': '认知留痕',
    'records.description': '记录合作过程中的重要时刻',
    'record.add': '新建记录',
    'record.type.communication': '沟通记录',
    'record.type.dispute': '分歧记录',
    'record.type.mediation': '协调记录',
    'record.visibility.authorized': '授权可见',
    'record.visibility.private': '仅自己可见',
    'record.visibility.public': '公开',
    'access.title': '授权查询',
    'access.description': '管理信息访问权限',
    'nav.authorization': '授权查询',
    'authorization.title': '授权查询',
    'authorization.description': '查询和管理您的信息授权记录',
    'authorization.grant': '查询授权',
    'authorization.revoke': '撤销授权',
    'authorization.records': '授权记录',
    'authorization.query': '授权查询',
    'authorization.entity': '授权对象',
    'authorization.scope': '授权范围',
    'authorization.expiry': '有效期至',
    'authorization.status': '状态',
    'authorization.granted': '已授权',
    'authorization.pending': '待确认',
    'authorization.expired': '已过期',
    'authorization.revoked': '已撤销',
  },
  en: {
    'app.name': 'Trust Station',
    'app.subtitle': '正心正念，互相成就',
    'app.slogan': 'Trust is not evaluated, but recorded, verified, and accumulated through real interactions',
    'nav.home': 'Home',
    'nav.community': 'Consensus & Guide',
    'nav.dashboard': 'Dashboard',
    'nav.profile.mindset': 'Mindset Profile',
    'nav.profile.trust': 'Trust Profile',
    'nav.projects': 'Projects',
    'nav.activities': 'Activities',
    'nav.people': 'People',
    'nav.ai': 'AI Tools',
    'nav.templates': 'Public Profile',
    'nav.relationships': 'Relationships',
    'nav.records': 'Records',
    'nav.cooperation': 'Cooperation',
    'nav.archives': 'Records',
    'nav.access': 'Access',
    'nav.mediation': 'Mediation',
    'nav.salons': 'Salons',
    'nav.communities': 'Communities',
    'nav.mindset': 'Mindset Profile',
    'nav.profile': 'My Info',
    'nav.search': 'Search',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.empty': 'No data',
    'common.more': 'View more',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.all': 'All',
    'common.view': 'View',
    'auth.login.title': 'Login',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.remember': 'Remember me',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.button': 'Login',
    'auth.login.noAccount': "Don't have an account?",
    'auth.register.title': 'Register',
    'auth.register.name': 'Real Name',
    'auth.register.email': 'Email',
    'auth.register.password': 'Password',
    'auth.register.confirmPassword': 'Confirm Password',
    'auth.register.agreement': 'I have read and agree to the Trust Commitment',
    'auth.register.button': 'Complete Registration',
    'auth.register.hasAccount': 'Already have an account?',
    'home.hero.title': 'Trust Station',
    'home.hero.subtitle': 'Global Business Trust Ledger',
    'home.hero.description': 'Trust is not evaluated, but recorded through real interactions',
    'home.hero.start': 'Get Started',
    'home.feature.consensus': 'Fundamental Consensus',
    'home.feature.consensus.desc': 'Equality, Respect, Sincerity, Mutual Benefit, Mutual Achievement',
    'home.feature.trace': 'Communication Consensus',
    'home.feature.trace.desc': 'Positive Thinking, Constructive Communication, Constructive Correction',
    'home.feature.auth': 'Multi-party Authorization',
    'home.feature.auth.desc': 'Sensitive information requires authorization',
    'home.feature.mindset': 'Mindset Growth',
    'home.feature.mindset.desc': 'Mindful practice, observe without attachment, rest in the present',
    'home.highlight.privacy': 'No Disclosure Required',
    'home.highlight.privacy.desc': 'Protect Privacy and Trade Secrets, Query with Consent',
    'home.highlight.neutral': 'Platform Neutrality',
    'home.highlight.neutral.desc': 'Record facts without judgment',
    'home.highlight.blockchain': 'Traceability',
    'home.highlight.blockchain.desc': 'Blockchain verification, tamper-proof',
    'home.cta.title': 'Start Your Trust Journey',
    'home.cta.description': 'Join Trust Station, make every collaboration traceable',
    'home.cta.button': 'Register Now',
    'home.disclaimer': 'This platform does not make value judgments on any disputes',
    'dashboard.welcome': 'Welcome back',
    'dashboard.description': 'Manage your trust relationships and records',
    'dashboard.stats.relationships': 'Relationships',
    'dashboard.stats.records': 'Records',
    'dashboard.stats.requests': 'Pending Requests',
    'dashboard.activity.title': 'Recent Activity',
    'dashboard.activity.newRelationship': 'Created new relationship',
    'dashboard.activity.newRecord': 'Added new record',
    'dashboard.activity.newRequest': 'Received new authorization request',
    'dashboard.quick.title': 'Quick Actions',
    'dashboard.quick.newRelationship': 'New Relationship',
    'dashboard.quick.newRecord': 'Add Record',
    'dashboard.quick.search': 'Search Access',
    'dashboard.quick.mediation': 'Mediation Center',
    'relationship.title': 'Relationship Management',
    'relationship.description': 'Manage your business relationships',
    'relationship.create': 'Create Relationship',
    'relationship.search': 'Search relationships...',
    'relationship.type.all': 'All Types',
    'relationship.type.business': 'Business',
    'relationship.type.investment': 'Investment',
    'relationship.type.partnership': 'Partnership',
    'relationship.type.employment': 'Employment',
    'relationship.status.all': 'All Status',
    'relationship.status.active': 'Active',
    'relationship.status.ended': 'Ended',
    'relationship.status.disputed': 'Disputed',
    'relationship.table.title': 'Title',
    'relationship.table.type': 'Type',
    'relationship.table.status': 'Status',
    'relationship.table.participants': 'Participants',
    'relationship.table.date': 'Start Date',
    'mediation.title': 'Mediation Center',
    'mediation.description': 'Introduce third-party mediators for fair dispute resolution',
    'mediation.apply': 'Apply for Mediation',
    'mediation.status.pending': 'In Progress',
    'mediation.status.resolved': 'Resolved',
    'mediation.status.failed': 'Failed',
    'mediation.mediator': 'Mediator',
    'mediation.parties': 'Parties',
    'mediation.description.label': 'Description',
    'profile.title': 'Profile',
    'profile.overview': 'Overview',
    'profile.stats': 'Statistics',
    'profile.trustScore': 'Trust Score',
    'profile.relationships': 'Relationships',
    'profile.records': 'Records',
    'profile.edit': 'Edit Profile',
    'mindset.title': 'Mindset Profile',
    'mindset.description': 'Record your mindfulness and growth journey',
    'mindset.level': 'Mindset Level',
    'mindset.practice': 'Practice Records',
    'mindset.reflection': 'Reflection Journal',
    'activities.title': 'Activities',
    'activities.description': 'Discover and participate in various activities',
    'activities.upcoming': 'Upcoming',
    'activities.ongoing': 'Ongoing',
    'activities.ended': 'Ended',
    'projects.title': 'Projects',
    'projects.description': 'Explore and manage your projects',
    'salons.title': 'Mindfulness Salons',
    'salons.subtitle': 'Explore inner self, build deep connections',
    'communities.title': 'Growth Communities',
    'communities.subtitle': 'Grow together with like-minded partners',
    'people.title': 'Discover Partners',
    'people.description': 'Find like-minded partners',
    'people.searchPlaceholder': 'Search by email...',
    'people.search': 'Search Partners',
    'people.following': 'Following',
    'common.participants': ' participants',
    'activity.create': 'Create Activity',
    'activity.online': 'Online',
    'activity.offline': 'Offline',
    'communities.create': 'Create Collective',
    'communities.join': 'Join',
    'communities.members': ' members',
    'communities.searchPlaceholder': 'Search collectives...',
    'records.title': 'Records',
    'records.description': 'Record important moments in your collaboration',
    'record.add': 'Add Record',
    'record.type.communication': 'Communication',
    'record.type.dispute': 'Dispute',
    'record.type.mediation': 'Mediation',
    'record.visibility.authorized': 'Authorized',
    'record.visibility.private': 'Private',
    'record.visibility.public': 'Public',
    'access.title': 'Access Control',
    'access.description': 'Manage information access permissions',
    'nav.authorization': 'Authorization',
    'authorization.title': 'Authorization',
    'authorization.description': 'Query and manage your information authorization records',
    'authorization.grant': 'Query Authorization',
    'authorization.revoke': 'Revoke Authorization',
    'authorization.records': 'Authorization Records',
    'authorization.query': 'Authorization Query',
    'authorization.entity': 'Authorized Entity',
    'authorization.scope': 'Authorization Scope',
    'authorization.expiry': 'Valid Until',
    'authorization.status': 'Status',
    'authorization.granted': 'Granted',
    'authorization.pending': 'Pending',
    'authorization.expired': 'Expired',
    'authorization.revoked': 'Revoked',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language;
      if (saved && (saved === 'zh' || saved === 'en')) {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
